# Generated by Django 5.0.6 on 2024-07-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_items_creator_alter_items_subcat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='item',
        ),
        migrations.AddField(
            model_name='category',
            name='subcats',
            field=models.ManyToManyField(blank=True, related_name='categories', to='base.subcat'),
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='users_items', to='base.items'),
        ),
        migrations.AlterField(
            model_name='items',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.items'),
        ),
    ]
