# Generated by Django 5.0.6 on 2024-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_items_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='colour',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
