# Generated by Django 5.0.6 on 2024-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_category_subcat_remove_user_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='logo.png', null=True, upload_to=''),
        ),
    ]
