# Generated by Django 5.0.6 on 2024-08-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcats',
        ),
        migrations.AddField(
            model_name='subcat',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='base.category'),
            preserve_default=False,
        ),
    ]
